apiVersion: secrets-store.csi.x-k8s.io/v1alpha1
kind: SecretProviderClass
metadata:
  name: serviceconnector-secretprovider
spec:
  provider: azure
  secretObjects:                                 # [OPTIONAL] SecretObject defines the desired state of synced K8s secret objects
  - secretName: serviceconnector-secret
    type: Opaque
    data: 
    - objectName: houk-secret                    # name of the mounted content to sync. this could be the object name or object alias 
      key: houk-secret
    - objectName: houk-secret2                    # name of the mounted content to sync. this could be the object name or object alias 
      key: houk-secret2
  parameters:
    usePodIdentity: "false"                      
    useVMManagedIdentity: "true"          # Set to true for using managed identity
    userAssignedIdentityID: 4b0601b3-2087-4421-80b2-d393ba2fc257   # Set the clientID of the user-assigned managed identity to use
    keyvaultName: houk-kv               # the name of the KeyVault
    objects: |
      array:
        - |
          objectName: houk-secret
          objectType: secret
        - |
          objectName: houk-secret2
          objectType: secret
    tenantId: "72f988bf-86f1-41af-91ab-2d7cd011db47"                             # the tenant ID of the KeyVault